### ISSUE TITLE
domain env variable empty on container

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-docker-collabora#9]
### Type of Report

bug

### Actual behaviour

below example works:
```yaml
- name: Start container
  docker_container:
    name: "{{ wtd_docker_collabora_name }}"
    image: "{{ wtd_docker_collabora_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ wtd_docker_collabora_ports }}"
    env:
      domain: "cloud\\.example\\.com"
    capabilities:
      - "{{ wtd_docker_collabora_capabilities }}"
```
below example does not work with
```yaml
wtd_docker_collabora_domains: "cloud\\.example\\.com"
```
```yaml
- name: Start container
  docker_container:
    name: "{{ wtd_docker_collabora_name }}"
    image: "{{ wtd_docker_collabora_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ wtd_docker_collabora_ports }}"
    env:
      domain: "{{ wtd_docker_collabora_domains }}"
    capabilities:
      - "{{ wtd_docker_collabora_capabilities }}"
```

### Expected behaviour

```bash
docker exec <container-id> env
..
domain=cloud\.example\.com
..
```
